# Generated by Django 6.0.6 on 2026-07-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
